# Generated by Django 5.2.9 on 2026-02-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterroom',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
