# Generated by Django 5.2.9 on 2026-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_recruiterroom_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesubmission',
            name='skills',
            field=models.TextField(default='No skills identified'),
        ),
    ]
