# Generated by Django 5.2.9 on 2026-03-04 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_resumesubmission_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resumesubmission',
            constraint=models.UniqueConstraint(fields=('room', 'candidate'), name='unique_candidate_submission_per_room'),
        ),
    ]
