# Generated by Django 5.2.9 on 2026-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_resumesubmission_unique_candidate_submission_per_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_weight', models.FloatField(default=0.6)),
                ('hard_skill_weight', models.FloatField(default=0.4)),
                ('keyword_sensitivity', models.CharField(choices=[('STR', 'Strict (Exact Match)'), ('FLX', 'Flexible (Synonym Expansion)')], default='FLX', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
