# Generated by Django 5.2.9 on 2026-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_globalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={},
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='keyword_sensitivity',
            field=models.CharField(choices=[('STR', 'Strict'), ('FLX', 'Flexible')], default='FLX', max_length=3),
        ),
    ]
