# Generated by Django 5.2.9 on 2026-05-09 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0006_alter_globalsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesubmission',
            name='is_premium_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumesubmission',
            name='referral_click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumesubmission',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
