# Generated by Django 5.2.9 on 2026-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0007_resumesubmission_is_premium_unlocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interviewing'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
