# Generated by Django 5.2.9 on 2026-05-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0009_profile_bio_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesubmission',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumesubmission',
            name='interview_location',
            field=models.CharField(blank=True, help_text='e.g., Google Meet Link or Office Address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumesubmission',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumesubmission',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('ON-SITE', 'On-Site')], max_length=20, null=True),
        ),
    ]
