# Generated by Django 5.2.9 on 2026-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0010_resumesubmission_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
