# Generated by Django 5.2.9 on 2026-05-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0011_profile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesubmission',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
