# Generated by Django 5.2.9 on 2026-05-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0012_resumesubmission_missing_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterroom',
            name='custom_weightage',
            field=models.JSONField(blank=True, help_text='Custom AI weights for this room (Overrides Global Settings).', null=True),
        ),
    ]
