# Generated by Django 5.2.9 on 2026-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0013_recruiterroom_custom_weightage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'Global AI Setting', 'verbose_name_plural': 'Global AI Settings'},
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='hard_skill_weight',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='semantic_weight',
        ),
        migrations.RemoveField(
            model_name='recruiterroom',
            name='custom_weightage',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='experience_weight',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='skill_weight',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='recruiterroom',
            name='experience_weight',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='recruiterroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recruiterroom',
            name='keyword_sensitivity',
            field=models.CharField(choices=[('STR', 'Strict'), ('FLX', 'Flexible')], default='FLX', max_length=3),
        ),
        migrations.AddField(
            model_name='recruiterroom',
            name='skill_weight',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='resumesubmission',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
